### ISSUE TITLE
Shows Auth failed as server response error, status:  404, lite-http-tunnel error. How to solve?

### ISSUE THREAD

**Issue by Learnr4Namish** [web-tunnel/lite-http-tunnel#11]
Unable to get JWT token. How to solve this issue?

**Comment by Learnr4Namish** [comment]
Used npx lite-http-tunnel to get JWT token. But the server returns this error.

**Comment by embbnux** [comment]
hi @Learnr4Namish Do you set JWT_GENERATOR_USERNAME and JWT_GENERATOR_PASSWORD environment variables in tunnel server. And which version of tunnel server do you deploy?

**Comment by Learnr4Namish** [comment]
Yes I have set and It is working fine now! Thank you!

**Comment by embbnux** [comment]
you are welcome!
