### ISSUE TITLE
Error: connect ECONNREFUSED ::1:8080

### ISSUE THREAD

**Issue by glorinli** [web-tunnel/lite-http-tunnel#3]
Hi, I got the following error.

GET:  /
Error: connect ECONNREFUSED ::1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 8080
}

Platform: MacOS 10.15.7
Server: web.py (python3)

**Comment by embbnux** [comment]
It seems IPV6 issue. Your "localhost" is ipv6, but your local server bind in ipv4. You can try with:
```bash
$ lite-http-tunnel start 8080 --host 127.0.0.1
```
Or edit /etc/hosts to make localhost to ipv4

**Comment by glorinli** [comment]
Add `--host 127.0.0.1` works!!!
